from .signal_copy_distance.config import SignalCopyConfig
from .signal_copy_distance.model import DistanceSignalCopyNet
from .signal_copy_distance.space import NeuronSpaceLayout, make_contiguous_layout
from .signal_copy_distance.trainer import train_signal_copy_distance
from .event_runtime import (
    Event,
    EventPayload,
    EventQueue,
    EventType,
    LateEventError,
    LocalClock,
    LocalTimestamp,
    PropagationDelay,
    QueueCapacityError,
)
from .canonical_neuron import TPCNNeuron
from .topology import BoundedTopology, Edge, TopologyCapacityError, TopologyError
from .predictive_coding import (
    LocalPredictor,
    Observation,
    PREDICTION_EVENT,
    PREDICTION_ERROR_EVENT,
    Prediction,
    PredictionCapacityError,
    PredictionError,
    PredictionResolution,
)
from .stroke_dataset import (
    CausalNormalizer,
    CharacterBoundary,
    DatasetMetadata,
    END_CHARACTER,
    LabeledCharacter,
    START_CHARACTER,
    STROKE_EVENT,
    StrokeEvent,
    StrokePoint,
    StrokeStreamEncoder,
    serialize_stream,
)
from .eligibility import (
    CreditAttribution,
    ELIGIBILITY_ACTIVITY_EVENT,
    EligibilityActivity,
    EligibilityCapacityError,
    EligibilityLedger,
    EligibilityTrace,
    REWARD_EVENT,
    RewardSignal,
)

__all__ = [
    "SignalCopyConfig",
    "DistanceSignalCopyNet",
    "NeuronSpaceLayout",
    "make_contiguous_layout",
    "train_signal_copy_distance",
    "Event",
    "EventPayload",
    "EventQueue",
    "EventType",
    "LateEventError",
    "LocalClock",
    "LocalTimestamp",
    "PropagationDelay",
    "QueueCapacityError",
    "TPCNNeuron",
    "BoundedTopology",
    "Edge",
    "TopologyCapacityError",
    "TopologyError",
    "LocalPredictor",
    "Observation",
    "PREDICTION_EVENT",
    "PREDICTION_ERROR_EVENT",
    "Prediction",
    "PredictionCapacityError",
    "PredictionError",
    "PredictionResolution",
    "CausalNormalizer",
    "CharacterBoundary",
    "DatasetMetadata",
    "END_CHARACTER",
    "LabeledCharacter",
    "START_CHARACTER",
    "STROKE_EVENT",
    "StrokeEvent",
    "StrokePoint",
    "StrokeStreamEncoder",
    "serialize_stream",
    "CreditAttribution",
    "ELIGIBILITY_ACTIVITY_EVENT",
    "EligibilityActivity",
    "EligibilityCapacityError",
    "EligibilityLedger",
    "EligibilityTrace",
    "REWARD_EVENT",
    "RewardSignal",
]